groups:
- name: mysql
  rules:
  
  - alert: MySQLReplicationError
    expr: mysql_slave_status_last_errno != 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Slave replication to {{ $labels.hostname }} failed"
      description: "The MySQL master at {{ $labels.master_host }} failed to replicate to slave {{ $labels.hostname }} with error code {{ $value }}."
